/**
 * Tests for the clean-room TS .ots parser/verifier.
 *
 * Vector-driven against fixtures generated by the Python helper:
 *  - fixture-01-mock.ots  — mock (offline) PendingAttestation
 *  - fixture-01-live.ots  — real submission to public OTS calendars at fixture creation time
 *
 * If the live fixture lacks Bitcoin attestations at test time (typical for fresh stamps —
 * confirmation takes 1-6 hours), the test asserts PendingAttestations are present instead.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  parseOts,
  verifyOtsAgainstFileDigest,
  HEADER_MAGIC,
  MAJOR_VERSION,
  TAG_BITCOIN_BLOCK_HEADER,
  TAG_PENDING,
} from '../../src/anchors/ots-verify.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const FIXTURE_DIR = join(__dirname, '..', '..', 'spec', 'v1', 'testvectors', 'ots')

const fixtureDigestHex = readFileSync(join(FIXTURE_DIR, 'fixture-01.digest.txt'), 'utf8').trim()
const fixtureDigest = Buffer.from(fixtureDigestHex, 'hex')
const mockOts = readFileSync(join(FIXTURE_DIR, 'fixture-01-mock.ots'))
const liveOtsPath = join(FIXTURE_DIR, 'fixture-01-live.ots')
const liveOtsAvailable = existsSync(liveOtsPath)
const liveOts = liveOtsAvailable ? readFileSync(liveOtsPath) : null

describe('header constants', () => {
  it('HEADER_MAGIC matches the OpenTimestamps spec', () => {
    expect(HEADER_MAGIC.length).toBe(31)
    expect(HEADER_MAGIC.toString('utf8', 1, 15)).toBe('OpenTimestamps')
  })
  it('MAJOR_VERSION = 1', () => {
    expect(MAJOR_VERSION).toBe(1)
  })
  it('Pending attestation tag matches spec', () => {
    expect(TAG_PENDING.toString('hex')).toBe('83dfe30d2ef90c8e')
  })
  it('Bitcoin attestation tag matches spec', () => {
    expect(TAG_BITCOIN_BLOCK_HEADER.toString('hex')).toBe('0588960d73d71901')
  })
})

describe('mock fixture (no calendar, single PendingAttestation)', () => {
  it('parses without error', () => {
    const result = parseOts(mockOts)
    expect(result.ok).toBe(true)
  })

  it('exposes the original file digest', () => {
    const result = parseOts(mockOts)
    expect(result.ok).toBe(true)
    if (result.ok) {
      expect(result.parsed.fileHashOp).toBe('sha256')
      expect(result.parsed.fileDigestHex).toBe(fixtureDigestHex)
    }
  })

  it('contains exactly one PendingAttestation pointing to the mock URL', () => {
    const result = parseOts(mockOts)
    expect(result.ok).toBe(true)
    if (result.ok) {
      expect(result.parsed.attestations.length).toBe(1)
      const att = result.parsed.attestations[0]!
      expect(att.kind).toBe('pending')
      if (att.kind === 'pending') {
        expect(att.calendarUrl).toBe('https://mock.calendar.example/')
      }
    }
  })

  it('verifyOtsAgainstFileDigest returns ok for the right digest, fails for the wrong one', () => {
    const right = verifyOtsAgainstFileDigest({ otsBytes: mockOts, expectedFileDigest: fixtureDigest })
    expect(right.ok).toBe(true)
    if (right.ok) {
      expect(right.bitcoinAnchored).toBe(false)
      expect(right.pendingCalendarUrls).toEqual(['https://mock.calendar.example/'])
    }
    const wrong = verifyOtsAgainstFileDigest({
      otsBytes: mockOts,
      expectedFileDigest: Buffer.alloc(32, 0xff),
    })
    expect(wrong.ok).toBe(false)
  })
})

describe('live fixture (real calendar attestations at stamp time)', () => {
  if (!liveOtsAvailable) {
    it.skip('skipped — fixture-01-live.ots not present (regenerate with generate-ots-fixtures)', () => {})
    return
  }
  const live = liveOts as Buffer

  it('parses without error', () => {
    const result = parseOts(live)
    if (!result.ok) {
      console.error('parse error:', result)
    }
    expect(result.ok).toBe(true)
  })

  it('exposes the original file digest', () => {
    const result = parseOts(live)
    expect(result.ok).toBe(true)
    if (result.ok) {
      expect(result.parsed.fileDigestHex).toBe(fixtureDigestHex)
    }
  })

  it('contains at least one attestation (PendingAttestation pre-confirmation, BitcoinBlockHeader after upgrade)', () => {
    const result = parseOts(live)
    expect(result.ok).toBe(true)
    if (result.ok) {
      expect(result.parsed.attestations.length).toBeGreaterThan(0)
      const kinds = new Set(result.parsed.attestations.map((a) => a.kind))
      // Right after stamping, expect at least one 'pending'; after upgrade, expect 'bitcoin'.
      expect(kinds.has('pending') || kinds.has('bitcoin')).toBe(true)
    }
  })

  it('verifyOtsAgainstFileDigest succeeds with the recorded digest', () => {
    const result = verifyOtsAgainstFileDigest({ otsBytes: live, expectedFileDigest: fixtureDigest })
    expect(result.ok).toBe(true)
  })
})

describe('malformed / adversarial inputs', () => {
  it('rejects empty buffer', () => {
    const result = parseOts(Buffer.alloc(0))
    expect(result.ok).toBe(false)
  })

  it('rejects buffer with wrong magic', () => {
    const result = parseOts(Buffer.from('not-an-ots-file', 'utf8'))
    expect(result.ok).toBe(false)
  })

  it('rejects buffer with only magic and no version', () => {
    const result = parseOts(HEADER_MAGIC)
    expect(result.ok).toBe(false)
  })

  it('rejects buffer with unsupported version', () => {
    // Magic + version=2 + nothing else
    const buf = Buffer.concat([HEADER_MAGIC, Buffer.from([0x02])])
    const result = parseOts(buf)
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.reason).toMatch(/unsupported major version/)
  })

  it('rejects buffer with trailing bytes after timestamp tree', () => {
    const withTrailing = Buffer.concat([mockOts, Buffer.from([0x00, 0x01, 0x02])])
    const result = parseOts(withTrailing)
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.reason).toMatch(/trailing bytes|unknown/i)
  })

  it('verifyOtsAgainstFileDigest fails fast if .ots cannot parse', () => {
    const result = verifyOtsAgainstFileDigest({
      otsBytes: Buffer.from('garbage', 'utf8'),
      expectedFileDigest: fixtureDigest,
    })
    expect(result.ok).toBe(false)
  })
})
