/**
 * Reference PDF→Fountain extractor tests.
 *
 * Exercises the FD-convention happy path (fixture-01-minimal), the
 * no-text-layer rejection (fixture-02), the corrupted-input rejection
 * (fixture-03), and a battery of input-validation guards.
 *
 * Fixtures are generated by scripts/generate-pdf-fixtures.py and committed
 * under spec/v1/testvectors/pdf-extraction/. Regenerate with:
 *   .venv/bin/python scripts/generate-pdf-fixtures.py
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import referenceExtractor, {
  ReferenceExtractor,
} from '../../src/extractors/reference/index.js'
import { ExtractorError } from '../../src/extractors/types.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const FIXTURE_DIR = join(__dirname, '..', '..', 'spec', 'v1', 'testvectors', 'pdf-extraction')

function loadFixture(name: string): Uint8Array {
  const buf = readFileSync(join(FIXTURE_DIR, name))
  return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength)
}

describe('ReferenceExtractor: identity', () => {
  it('exposes the expected name and version', () => {
    expect(referenceExtractor.name).toBe('screenreg-reference')
    expect(referenceExtractor.version).toMatch(/^\d+\.\d+\.\d+$/)
  })

  it('default export is a ready-to-use instance', () => {
    expect(referenceExtractor).toBeInstanceOf(ReferenceExtractor)
  })
})

describe('ReferenceExtractor: input validation', () => {
  it('rejects non-Uint8Array input', async () => {
    await expect(
      // @ts-expect-error — testing runtime guard
      referenceExtractor.extract([0x25, 0x50, 0x44, 0x46]),
    ).rejects.toMatchObject({ code: 'EXTRACT_CORRUPTED' })
  })

  it('rejects empty input', async () => {
    await expect(referenceExtractor.extract(new Uint8Array(0))).rejects.toMatchObject({
      code: 'EXTRACT_CORRUPTED',
    })
  })

  it('rejects input that does not start with the PDF magic', async () => {
    const fake = new TextEncoder().encode('not a pdf')
    await expect(referenceExtractor.extract(fake)).rejects.toMatchObject({
      code: 'EXTRACT_CORRUPTED',
    })
  })

  it('rejects input exceeding the 32 MB cap', async () => {
    const huge = new Uint8Array(32 * 1024 * 1024 + 1)
    huge[0] = 0x25
    huge[1] = 0x50
    huge[2] = 0x44
    huge[3] = 0x46
    huge[4] = 0x2d
    await expect(referenceExtractor.extract(huge)).rejects.toMatchObject({
      code: 'EXTRACT_CORRUPTED',
    })
  })
})

describe('ReferenceExtractor: fixture-01-minimal (FD-convention happy path)', () => {
  it('extracts the expected Fountain elements with full confidence', async () => {
    const pdfBytes = loadFixture('fixture-01-minimal.pdf')
    const result = await referenceExtractor.extract(pdfBytes)
    expect(result.confidence).toBe(1)

    const f = result.fountain
    // Element checks — every line that drove this PDF MUST appear in the
    // extracted Fountain in the expected element position.
    expect(f).toContain('FADE IN:')
    expect(f).toContain('INT. KITCHEN - DAY')
    expect(f).toContain('A WRITER sits at a wooden table, staring at a blank screen.')
    expect(f).toContain('WRITER')
    expect(f).toContain('(quietly)')
    expect(f).toContain("Just one good line. That's all I need.")
    expect(f).toContain('VOICE (O.S.)')
    expect(f).toContain('You said that yesterday.')
    expect(f).toContain('> CUT TO:') // transition syntax per Fountain spec
    expect(f).toContain('EXT. ROOFTOP - NIGHT')
    expect(f).toContain('FADE OUT.')
  })

  it('emits character + parenthetical + dialogue as a contiguous block', async () => {
    const pdfBytes = loadFixture('fixture-01-minimal.pdf')
    const result = await referenceExtractor.extract(pdfBytes)
    const block = `WRITER\n(quietly)\nJust one good line. That's all I need.`
    expect(result.fountain).toContain(block)
  })

  it('does NOT emit page numbers as content', async () => {
    const pdfBytes = loadFixture('fixture-01-minimal.pdf')
    const result = await referenceExtractor.extract(pdfBytes)
    expect(result.fountain).not.toMatch(/^\s*1\.?\s*$/m)
    expect(result.fountain).not.toMatch(/^\s*2\.?\s*$/m)
  })

  it('output is deterministic for the same input', async () => {
    const pdfBytes = loadFixture('fixture-01-minimal.pdf')
    const a = await referenceExtractor.extract(pdfBytes)
    const b = await referenceExtractor.extract(pdfBytes)
    expect(a.fountain).toBe(b.fountain)
    expect(a.confidence).toBe(b.confidence)
  })

  it('produces valid UTF-8 (consumable by v1-strict normalization)', async () => {
    const pdfBytes = loadFixture('fixture-01-minimal.pdf')
    const result = await referenceExtractor.extract(pdfBytes)
    // TextDecoder with fatal:true throws on invalid UTF-8 — confirm we don't.
    const decoder = new TextDecoder('utf-8', { fatal: true })
    const bytes = new TextEncoder().encode(result.fountain)
    expect(() => decoder.decode(bytes)).not.toThrow()
  })

  it('returns a non-empty diagnostics array (one entry per page)', async () => {
    const pdfBytes = loadFixture('fixture-01-minimal.pdf')
    const result = await referenceExtractor.extract(pdfBytes)
    expect(result.diagnostics.length).toBeGreaterThanOrEqual(1)
  })
})

describe('ReferenceExtractor: fixture-02-no-text-layer', () => {
  // A PDF whose only content is drawn shapes (no text run) may surface as
  // EXTRACT_NO_TEXT_LAYER (pdf2json parses + reports zero text tokens) OR
  // EXTRACT_CORRUPTED (pdf2json refuses to parse the PDF at all because of
  // an XRef stream variant it doesn't handle). Both are acceptable
  // rejection outcomes — the contract is "reject loudly with a typed code".
  it('rejects with a typed extractor error (NO_TEXT_LAYER or CORRUPTED)', async () => {
    const pdfBytes = loadFixture('fixture-02-no-text-layer.pdf')
    await expect(referenceExtractor.extract(pdfBytes)).rejects.toThrow(ExtractorError)
    try {
      await referenceExtractor.extract(pdfBytes)
      throw new Error('expected throw')
    } catch (err) {
      expect(err).toBeInstanceOf(ExtractorError)
      const code = (err as ExtractorError).code
      expect(['EXTRACT_NO_TEXT_LAYER', 'EXTRACT_CORRUPTED']).toContain(code)
    }
  })
})

describe('ReferenceExtractor: fixture-03-corrupted', () => {
  it('rejects with EXTRACT_CORRUPTED', async () => {
    const pdfBytes = loadFixture('fixture-03-corrupted.pdf')
    await expect(referenceExtractor.extract(pdfBytes)).rejects.toMatchObject({
      code: 'EXTRACT_CORRUPTED',
    })
  })
})

describe('ReferenceExtractor: extracted Fountain round-trips through v1-strict', () => {
  it('the extracted Fountain produces a stable content hash via the shared normalizer', async () => {
    const { normalize, contentHashOfNormalized } = await import(
      '../../src/shared/normalize/v1-strict.js'
    )
    const pdfBytes = loadFixture('fixture-01-minimal.pdf')
    const a = await referenceExtractor.extract(pdfBytes)
    const b = await referenceExtractor.extract(pdfBytes)
    const aBytes = new TextEncoder().encode(a.fountain)
    const bBytes = new TextEncoder().encode(b.fountain)
    const aNorm = normalize(aBytes)
    const bNorm = normalize(bBytes)
    expect(aNorm.ok).toBe(true)
    expect(bNorm.ok).toBe(true)
    if (aNorm.ok && bNorm.ok) {
      const aHash = await contentHashOfNormalized(aNorm.normalized)
      const bHash = await contentHashOfNormalized(bNorm.normalized)
      expect(bHash).toBe(aHash)
      expect(aHash).toMatch(/^sha256:[0-9a-f]{64}$/)
    }
  })
})
